######################################################################
# Automatically generated by qmake (3.0) Thu Dec 6 17:18:49 2012
######################################################################

TEMPLATE = app
TARGET = IosWidgetApp
DEPENDPATH += .
INCLUDEPATH += /Volumes/Code/qt-src/qt-base-ios/mkspecs/common/ios .

# Input
SOURCES += main.cpp
QT+=widgets
